
  # PARAMETERS
  #Contiene todos los parámetros que serán utilizados en una petición http ya sea que sea enviado
  #por el header, path, query o cache  
  # parameters:
    id:
      name: id
      in: path
      required: true
      description: People id
      schema:
        type: integer 

    page:
      name: page
      in: query
      required: true
      description: The number of page
      schema:
        type: integer 
        
    amount:
      name: page
      in: query
      required: true
      description: The numbers of items to return for page
      schema:
        type: integer 

   
    