
  # PARAMETERS
  #Contiene todos los parámetros que serán utilizados en una petición http ya sea que sea enviado
  #por el header, path, query o cache  
  # parameters:
    id:
      name: id
      in: path
      required: true
      description: People id
      schema:
        type: integer 

    page:
      name: page
      in: query
      required: false
      description: The number of page
      schema:
        type: integer 
        
    limit:
      name: limit
      in: query
      required: false
      description: The numbers of items max to return for page
      schema:
        type: integer 

    quest:
      name: quest
      in: query
      required: false
      description: Query to search
      schema:
        type: string 

   
    